name: 'Test Site for School '
favicon: null
layout_spectrum: 0.4811977476347238
typography_spectrum: 0.7485641059465706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3959010844118893
  lightness: 0.29357674065977335
  saturation: 0.4024877971969545
  rhythmicContrast: 0.6186078020837158
purpose: []
