analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9197995
  brandStrength: 0.9630326
  lightness: 0.8577694
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.9348371
typography_spectrum: 0.2825814
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: 'Test Site for School '
